Admin.create!(email: 'homer@admin.com', password: 'admin1234', password_confirmation: 'admin1234')

rep_one = CompanyRep.create!(email: 'jeffery@company.com', password: 'company1234', password_confirmation: 'company1234')
company_one = Company.create!(company_rep_id: rep_one.id, name: "AwesomeCo", address: "111 1st st", city: "Eau Claire", state: "WI", zip_code: "54703", rejected: false, approved: false)
job_one = Job.create!(company_id: company_one.id, title: "Web Developer", job_type: "Entry Level - Salary", job_status: "Full-Time", job_description: "Build cool things for cool people with cool tools.", hours_per_week: 45, pay_min: 60000, pay_max: 100000, pay_comment: "Do your work. You'll get paid", applicant_experience: "You should have an active GitHub account.", how_to_apply: "Send resume to awesome_hr@awesomeco.com", job_location: "1234 Five St, Sunny, CA", approved: false)
job_two = Job.create!(company_id: company_one.id, title: "Elixir Developer", job_type: "Entry Level - Salary", job_location: "remote", job_status: "Full-Time", job_description: "Be awesome at all times and do awesome stuff.", hours_per_week: 40, pay_min: 75000, pay_max: 100000, pay_comment: "Prove yourself and after three months we'll sweeten the pot.", applicant_experience: "Have a github account with some Elixir stuff and you're golden.", how_to_apply: "We'll contact you if we're interested. Don't worry, we're magic.", approved: true, rejected: false)

rep_two = CompanyRep.create!(email: 'walter@company.com', password: 'company1234', password_confirmation: 'company1234')
company_two = Company.create!(company_rep_id: rep_two.id, name: "Office Max", address: "222 2nd st", city: "Eau Claire", state: "WI", zip_code: "54703", rejected: false, approved: true)
job_three = Job.create!(company_id: company_two.id, title: "Sales", job_type: "Entry Level - Salary", job_status: "Intership", job_description: "Selling Electronics and dealing with Customers", hours_per_week: 40, pay_min: 30.0, pay_max: nil, pay_comment: "Will discuss", applicant_experience: "none", how_to_apply: "In person", job_location: "111 First St", approved:true)

rep_three = CompanyRep.create!(email: 'donny@company.com', password: 'company1234', password_confirmation: 'company1234')
company_three = Company.create!(company_rep_id: rep_three.id, name: "Farrell Equipment", address: "333 3rd st", city: "Eau Claire", state: "WI", zip_code: "54703", rejected: false, approved: true)
job_four = Job.create!(company_id: company_three.id, title: "Software Developer", job_type: "Entry Level - Salary", job_status: "Full-Time", job_description: "Developing Websites", hours_per_week: 40, pay_min: 50.0, pay_max: nil, pay_comment: "Will discuss", applicant_experience: "Associates degree", how_to_apply: "In person", job_location: "222 Second St", approved:true)

rep_four = CompanyRep.create!(email: 'maude@company.com', password: 'company1234', password_confirmation: 'company1234')
company_four = Company.create!(company_rep_id: rep_four.id, name: "Labor Ready", address: "444 4th st", city: "Eau Claire", state: "WI", zip_code: "54703", rejected: false, approved: true)
job_five = Job.create!(company_id: company_four.id, title: "Laborer", job_type: "Entry Level - Salary", job_status: "Temporary", job_description: "Hard work and get paid less", hours_per_week: 60, pay_min: 15.0, pay_max: nil, pay_comment: "minimal wage", applicant_experience: "none", how_to_apply: "In person", job_location: "333 Third St", approved:true)

rep_five = CompanyRep.create!(email: 'jackie@company.com', password: 'company1234', password_confirmation: 'company1234')
company_five = Company.create!(company_rep_id: rep_five.id, name: "Apple", address: "2222 Second st", state: "CA", city: "Cupertino", zip_code: "22222", company_rep_id: 2, approved: false, rejected: false)
job_six = Job.create!(company_id: company_five.id, title: "Secrecy Specialist", job_type: "Entry Level - Salary", job_location: "remote", job_status: "Full-Time", job_description: "Make sure no one knows what we're up to so we don't have to kill them.", hours_per_week: 50, pay_min: 200000, pay_max: 250000, pay_comment: "We do stuff that's bigger than you're worth.", applicant_experience: "We can not disclose that information.", how_to_apply: "Tape your resume under the mailbox at 4th and Jameson. Someone will be in touch.", approved: false, rejected: false,)

rep_six = CompanyRep.create!(email: 'bunny@company.com', password: 'company1234', password_confirmation: 'company1234')
company_six = Company.create!(company_rep_id: rep_six.id, name: "Wayne Enter Prizes", address: "3333 Third st", state: "CA", city: "Cupertino", zip_code: "33333", company_rep_id: 3, approved: false, rejected: false)
job_seven = Job.create!(company_id: company_six.id, title: "Action Hero Sidekick", job_type: "Internship - Salary", job_location: "Eau Claire", job_status: "Part-Time", job_description: "With great power come great responsibility. As a sidekick, you can learn both.", hours_per_week: 20, pay_min: 15.75, pay_max: 17.00, pay_comment: "The only reward you should need is that satisfaction you receive from the good you do, but we'll give you a little bit.", applicant_experience: "Fearlessness in the face of pure evil. Some sort of tragic back-story is preferred. Flexible schedule.", how_to_apply: "Just talk to the police chief. He'll pretend he has no idea what you're talking about, but I'll get the message.", approved: false, rejected: false)
job_eight = Job.create!(company_id: Company.find_by(name: "Wayne Enter Prizes").id, title: "Nerf Gun Engineer", job_type: "Entry Level - Salary", job_location: "Lake Halle", job_status: "Full-Time", job_description: "The only thing better than excessive violence is excessive violence that won't hurt anyone. We need you to design the tools that our customers can use to make this dream a reality.", hours_per_week: 45, pay_min: 80000, pay_max: 90000, pay_comment: "Obviously you will receive a full arsenal at your disposal limited only by the depth of you imagination.", applicant_experience: "Must have fairly extensive design and tactical training.", how_to_apply: "Send us a sketch or prototype of your dream Nerf weapon. If we like it, we'll give you an offer.", approved: false, rejected: false)

rep_seven = CompanyRep.create!(email: 'smokie@company.com', password: 'company1234', password_confirmation: 'company1234')
company_seven = Company.create!(company_rep_id: rep_seven.id, name: "Chuck E. Cheese's", address: "4444 Fourth st", state: "WI", city: "Eau Claire", zip_code: "44444", company_rep_id: 4, approved: false, rejected: false)
job_nine = Job.create!(company_id: company_seven.id, title: "Pizza Recipe Specialist", job_type: "Entry Level - Salary", job_location: "Chippewa Falls", job_status: "Full-Time", job_description: "Create amazing pizza concoctions for our customers.", hours_per_week: 40, pay_min: 40000, pay_max: 60000, pay_comment: "Make us money and you make more.", applicant_experience: "Extensive experience with all types of pizza toppings (ie: pepperoni, onions, buffalo wings).", how_to_apply: "Stop by for a slice and drop off your resume.", approved: false, rejected: false)

rep_eight = CompanyRep.create!(email: 'brandt@company.com', password: 'company1234', password_confirmation: 'company1234')
company_eight= Company.create!(company_rep_id: rep_eight.id, name: "Irish Distillers Limited USA Satellite Office", address: "5555 Fifth st", state: "MN", city: "Saint Paul", zip_code: "55555", company_rep_id: 4, approved: false, rejected: false)
job_ten = Job.create!(company_id: company_eight.id, title: "Jameson Quality Assurance", job_type: "Internship - Hourly", job_location: "remote", job_status: "Part-Time", job_description: "We'll send you a bottle from each batch. You must commit to drinking at least half of the bottle and writing a full report before we ship.", hours_per_week: 10, pay_min: 15, pay_max: 20, pay_comment: "You get free Jameson every week as well.", applicant_experience: "Good taste buds that have tasted a a fair amount of fine liquor.", how_to_apply: "The application is on the underside of all 18 Year Old Limited Reserve and Rarest Vintage Reserve labels.", approved: false, rejected: false)
